[general]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false
[[datasets]]
image_directory = "C:/AI/apps/musubi-tuner/files/datasets/prince_harry/256"
cache_directory = "C:/AI/apps/musubi-tuner/files/datasets/prince_harry/256_cache"
num_repeats = 1
resolution = [256,256]
