[general]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "/mnt/c/AI/apps/musubi-tuner/files/datasets/Ed Milliband"
cache_directory = "/mnt/c/AI/apps/musubi-tuner/files/datasets/Ed Milliband_cache"
num_repeats = 1
resolution = [256,256]
