# Musubi Tuner Dataset Config Template
# Fill in the variables as needed for your batch or script

[general]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
image_directory = "@DATASET_PATH@"
cache_directory = "@CACHE_PATH@"
num_repeats = 1
resolution = [256, 256]

[training]
learning_rate = @LEARNING_RATE@
network_alpha = @NETWORK_ALPHA@
network_dim = @NETWORK_DIM@
max_data_loader_n_workers = @N_WORKERS@
max_train_epochs = @EPOCHS@
gradient_accumulation_steps = @GRAD_ACCUM@